export const GET_GIST_LIST = "GET_GIST_LIST";
export const SELECT_GIST = "SELECT_GIST";
export const GET_PROFILE_GISTS = "PROFILE_GISTS";
export const START_PROFILE_GISTS_LOADING = "START_PROFILE_GISTS_LOADING";
export const STOP_PROFILE_GISTS_LOADING = "STOP_PROFILE_GISTS_LOADING";

export const SET_PAGE_NUMBER = "SET_PAGE_NUMBER";
export const SET_LOGIN_STATE = "SET_LOGIN_STATE";
export const START_GIST_LOADING = "START_GIST_LOADING";
export const STOP_GIST_LOADING = "STOP_GIST_LOADING";
